### PR TITLE
Fix compilation error with GCC 14 due to missing header

### PR DESCRIPTION
**Pull request by ckreibich**
Zeek 6.2 no longer compiles with GCC 14.1.1 (the default on Fedora 40):
```
/home/christian/devel/zeek/broker/tests/benchmark/broker-benchmark.cc: In function ‘broker::list_builder {anonymous}::createEventArgs()’:
/home/christian/devel/zeek/broker/tests/benchmark/broker-benchmark.cc:138:12: error: ‘sort’ is not a member of ‘std’; did you mean ‘qsort’?
  138 |       std::sort(keys.begin(), keys.end());
      |            ^~~~
      |            qsort
/home/christian/devel/zeek/broker/tests/benchmark/broker-benchmark.cc:144:14: error: ‘sort’ is not a member of ‘std’; did you mean ‘qsort’?
  144 |         std::sort(vals.begin(), vals.end());
      |              ^~~~
      |              qsort
make[3]: *** [tests/CMakeFiles/broker-benchmark.dir/build.make:76: tests/CMakeFiles/broker-benchmark.dir/benchmark/broker-benchmark.cc.o] Error 1
```

I'm going to mark this down on the list of issues for upcoming Zeek patch releases. Zeek 6.0 is not affected.

### CODE REVIEW

**Comment by ckreibich** [comment]
I don't get why clang-tidy is blowing up here. Did we miss the fact that it did so in the past? I've not gone near the things it's complaining about.

**Comment by timwoj** [comment]
Probably https://github.com/zeek/broker/issues/365

**Comment by Neverlord** [comment]
> I don't get why clang-tidy is blowing up here. Did we miss the fact that it did so in the past? I've not gone near the things it's complaining about. @timwoj, @Neverlord, I'd be grateful, thx...

The `noexcept`: clang-tidy is just right here. `std::map::find` isn't `noexcept`, so we can't (shouldn't) make functions that call that `noexcept`. The other warning I just suppressed for now, since it's not something we care about.

**Review by Neverlord — APPROVED** [review]

**Comment by Neverlord** [comment]
@timwoj can I pull this into `master` or is this going to be merged into a separate branch for Zeek 6.2?

**Comment by awelzel** [comment]
> @timwoj can I pull this into master or is this going to be merged into a separate branch for Zeek 6.2?

This PR is marked/labeled for `release/zeek-6.2` which is used for Zeek 6.2 (and IIUC part of the fixes are already in `master`).

So maybe open a new PR with just the clang-tidy fixes?

**Comment by awelzel** [comment]
@Neverlord and me chatted - not 100% sure what the plan is/was but seems

* we don't necessarily need the clang-tidy fixes for 6.2.1
* the header include fix we need though

So he'll force-push remove the clang-tidy fixes (and re-spin in a separate PR) and the rest of the fixes would be merged into `release/zeek-6.2` for 6.2.2.

**Comment by timwoj** [comment]
As a heads up, we won't be doing any more 6.0/6.2 releases once 7.0 is released.

**Comment by awelzel** [comment]
> As a heads up, we won't be doing any more 6.0/6.2 releases once 7.0 is released.

It might be that for 6.0 there's nothing interesting right now? But there's minimally the following in [Release Cadence](https://github.com/zeek/zeek/wiki/Release-Cadence):

> Once a new LTS release comes out, we will stop maintaining the previous one after one further feature release on top of that new LTS.

This PR concerns only 6.2 though IIUC.
